# Generated by Django 3.2.5 on 2021-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('listQ', models.TextField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
