# Generated by Django 3.2.5 on 2021-08-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0002_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u',
            name='listQ',
        ),
        migrations.RemoveField(
            model_name='u',
            name='score',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listQ', models.TextField()),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizmaker.u')),
            ],
        ),
    ]
