# Generated by Django 3.2.5 on 2021-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0003_auto_20210801_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Queiz',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
